export const OFFERS_TYPES = {
  GET_ALL_OFFERS: 'GET_ALL_OFFERS',
  GET_ALL_OFFERS_SUCCESS: 'GET_ALL_OFFERS_SUCCESS',
  GET_ALL_OFFERS_FAIL: 'GET_ALL_OFFERS_FAIL',

  GET_UNIQUE_OFFER: 'GET_UNIQUE_OFFER',
  GET_UNIQUE_OFFER_SUCCESS: 'GET_UNIQUE_OFFER_SUCCESS',
};

export const SHOPPING_CART_TYPES = {
  GET_SHOPPING_CART: 'GET_SHOPPING_CART',
  GET_SHOPPING_CART_SUCCESS: ' GET_SHOPPING_CART_SUCCESS',
};
